In [1]:
import numpy as np

In [2]:
keys = range(260)

In [4]:
keys = np.array(keys)
np.random.shuffle(keys)

In [10]:
train_size = 0.8
valid_size = 0.1
test_size = 0.1

In [11]:
keys[:int(train_size*len(keys))]

array([115, 223, 245,  89,  56,  88, 122, 199, 254, 136, 178,  98, 226,
       242, 160, 167,  83,  96, 194, 202, 241, 127,  42, 186, 187, 247,
        60,  75,   6, 138, 174,  99, 222,  61, 171,   3, 161, 198, 195,
       177, 229,  55, 104, 191,  48, 123, 117,  28,  79,  49,  97,  17,
        37,  25,  21,  26,  46,  90, 165,  53, 107, 139, 219, 215,  40,
       185,  51, 230, 101, 114,  84, 153, 238, 234,  34, 237, 258, 227,
       134, 207,  39,  93,  95, 156, 224, 256,  77, 119,  24,  54, 149,
       214,  50,  23,   1,  87,  45, 236, 151, 102, 216, 217, 200,  43,
        62, 246, 172, 130, 168, 250, 232,  74, 176,  59, 154,  12,  71,
       170, 197, 159,  19,  57,  66, 243, 188,  63, 211, 148, 140, 193,
        15, 169,  10, 145,  36, 163,   4,  92, 116, 218,  22,  81,  52,
        13,  72,  20, 111,  35,  70, 120,  29, 196,  69, 150, 166, 213,
       126, 239, 255,  64, 192, 184, 128,  82, 182, 142, 235,  76,  32,
       180, 257, 141, 152, 173, 162, 133, 221,  47, 220,   9, 20

In [12]:
keys[int(train_size*len(keys)):int((train_size+valid_size)*len(keys))]

array([  2,  31, 240, 179, 105, 164, 110, 132, 248,   0,  58,   5, 259,
       144, 103, 210, 129, 252,  41, 106, 137, 121, 146, 125,  86, 212])

In [13]:
keys[int((train_size+valid_size)*len(keys)):]

array([ 30, 175,  65, 203, 205,  44,  27,  80, 253, 181, 113, 143, 204,
         7, 208, 158, 112, 155, 190, 231, 228,   8,  73, 118, 189, 206])

In [9]:
np.array(keys)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18